# -*- coding: utf-8 -*-

"""
    File with all currently supported (and some more) specification on segments, such as dict of tags
    for supported versions, qualifiers for them
"""

_segment_structure = {
    "D96A": {
        "ADR": [  # ADDRESS
            ("C817", "C"),
            ("C090", "C"),
            ("3164", "C"),
            ("3251", "C"),
            ("3207", "C"),
            ("C819", "C"),
            ("C517", "C"),
        ],
        "AGR": [  # AGREEMENT IDENTIFICATION
            ("C543", "C"),
            ("9419", "C"),
        ],
        "AJT": [  # ADJUSTMENT DETAILS
            ("4465", "M"),
            ("1082", "C"),
        ],
        "ALC": [  # ALLOWANCE OR CHARGE
            ("5463", "M"),
            ("C552", "C"),
            ("4471", "C"),
            ("1227", "C"),
            ("C214", "C"),
        ],
        "ALI": [  # ADDITIONAL INFORMATION
            ("3239", "C"),
            ("9213", "C"),
            ("4183", "C"),
            ("4183", "C"),
            ("4183", "C"),
            ("4183", "C"),
            ("4183", "C"),
        ],
        "APR": [  # ADDITIONAL PRICE INFORMATION
            ("4043", "C"),
            ("C138", "C"),
            ("C960", "C"),
        ],
        "ARD": [  # AMOUNTS RELATIONSHIP DETAILS
            ("C549", "C"),
        ],
        "ARR": [  # ARRAY INFORMATION
            ("C778", "C"),
            ("C770", "C"),
        ],
        "ASI": [  # ARRAY STRUCTURE IDENTIFICATION
            ("C779", "M"),
            ("C082", "C"),
            ("4405", "C"),
            ("4513", "C"),
        ],
        "ATT": [  # ATTRIBUTE
            ("9017", "M"),
            ("C955", "C"),
            ("C956", "C"),
        ],
        "AUT": [  # AUTHENTICATION RESULT
            ("9280", "M"),
            ("9282", "C"),
        ],
        "BGM": [  # BEGINNING OF MESSAGE
            ("C002", "C"),
            ("1004", "C"),
            ("1225", "C"),
            ("4343", "C"),
        ],
        "BII": [  # STRUCTURE IDENTIFICATION
            ("7429", "M"),
            ("C045", "M"),
            ("7140", "C"),
        ],
        "BUS": [  # BUSINESS FUNCTION
            ("C521", "C"),
            ("3279", "C"),
            ("4487", "C"),
            ("C551", "C"),
            ("4463", "C"),
        ],
        "CAV": [  # CHARACTERISTIC VALUE
            ("C889", "M"),
        ],
        "CCD": [  # CREDIT COVER DETAILS
            ("4505", "C"),
            ("4507", "C"),
            ("4509", "C"),
        ],
        "CCI": [  # CHARACTERISTIC/CLASS ID
            ("7059", "C"),
            ("C502", "C"),
            ("C240", "C"),
        ],
        "CDI": [  # PHYSICAL OR LOGICAL STATE
            ("7001", "M"),
            ("C564", "M"),
        ],
        "CDS": [  # CODE SET IDENTIFICATION
            ("C702", "M"),
            ("1507", "C"),
            ("4513", "C"),
        ],
        "CDV": [  # CODE VALUE DEFINITION
            ("9426", "M"),
            ("9434", "C"),
            ("4513", "C"),
        ],
        "CED": [  # COMPUTER ENVIRONMENT DETAILS
            ("1501", "M"),
            ("C079", "M"),
        ],
        "CMP": [  # COMPOSITE DATA ELEMENT IDENTIFICATION
            ("9146", "M"),
            ("1507", "C"),
            ("4513", "C"),
        ],
        "CNI": [  # CONSIGNMENT INFORMATION
            ("1490", "C"),
            ("C503", "C"),
            ("1312", "C"),
        ],
        "CNT": [  # CONTROL TOTAL
            ("C270", "M"),
        ],
        "COD": [  # COMPONENT DETAILS
            ("C823", "C"),
            ("C824", "C"),
        ],
        "COM": [  # COMMUNICATION CONTACT
            ("C076", "M"),
        ],
        "COT": [  # CONTRIBUTION DETAILS
            ("5047", "M"),
            ("C953", "C"),
            ("C522", "C"),
            ("C203", "C"),
            ("C960", "C"),
        ],
        "CPI": [  # CHARGE PAYMENT INSTRUCTIONS
            ("C229", "C"),
            ("C231", "C"),
            ("4237", "C"),
        ],
        "CPS": [  # CONSIGNMENT PACKING SEQUENCE
            ("7164", "M"),
            ("7166", "C"),
            ("7075", "C"),
        ],
        "CST": [  # CUSTOMS STATUS OF GOODS
            ("1496", "C"),
            ("C246", "C"),
            ("C246", "C"),
            ("C246", "C"),
            ("C246", "C"),
            ("C246", "C"),
        ],
        "CTA": [  # CONTACT INFORMATION
            ("3139", "C"),
            ("C056", "C"),
        ],
        "CUX": [  # CURRENCIES
            ("C504", "C"),
            ("C504", "C"),
            ("5402", "C"),
            ("6341", "C"),
        ],
        "DAM": [  # DAMAGE
            ("7493", "M"),
            ("C821", "C"),
            ("C822", "C"),
            ("C825", "C"),
            ("C826", "C"),
        ],
        "DGS": [  # DANGEROUS GOODS
            ("8273", "C"),
            ("C205", "C"),
            ("C234", "C"),
            ("C223", "C"),
            ("8339", "C"),
            ("8364", "C"),
            ("8410", "C"),
            ("8126", "C"),
            ("C235", "C"),
            ("C236", "C"),
            ("8255", "C"),
            ("8325", "C"),
            ("8211", "C"),
        ],
        "DII": [  # DIRECTORY IDENTIFICATION
            ("1056", "M"),
            ("1058", "M"),
            ("9148", "C"),
            ("1476", "C"),
            ("3453", "C"),
            ("4513", "C"),
        ],
        "DIM": [  # DIMENSIONS
            ("6145", "M"),
            ("C211", "M"),
        ],
        "DLI": [  # DOCUMENT LINE IDENTIFICATION
            ("1073", "M"),
            ("1082", "M"),
        ],
        "DLM": [  # DELIVERY LIMITATIONS
            ("4455", "C"),
            ("C522", "C"),
            ("C214", "C"),
            ("4457", "C"),
        ],
        "DMS": [  # DOCUMENT/MESSAGE SUMMARY
            ("1004", "C"),
            ("1001", "C"),
            ("7240", "C"),
        ],
        "DOC": [  # DOCUMENT/MESSAGE DETAILS
            ("C002", "M"),
            ("C503", "C"),
            ("3153", "C"),
            ("1220", "C"),
            ("1218", "C"),
        ],
        "DSI": [  # DATA SET IDENTIFICATION
            ("C782", "M"),
            ("C082", "C"),
            ("4405", "C"),
            ("C286", "C"),
            ("1060", "C"),
        ],
        "DTM": [  # DATE/TIME/PERIOD
            ("C507", "M"),
        ],
        "EFI": [  # EXTERNAL FILE LINK IDENTIFICATION
            ("C077", "M"),
            ("C099", "C"),
            ("1050", "C"),
        ],
        "ELM": [  # SIMPLE DATA ELEMENT DETAILS
            ("9150", "M"),
            ("9153", "C"),
            ("9155", "C"),
            ("9156", "C"),
            ("9158", "C"),
            ("9161", "C"),
            ("1507", "C"),
            ("4513", "C"),
        ],
        "ELU": [  # DATA ELEMENT USAGE DETAILS
            ("9162", "M"),
            ("7299", "C"),
            ("1050", "C"),
            ("4513", "C"),
        ],
        "EMP": [  # EMPLOYMENT DETAILS
            ("9003", "M"),
            ("C948", "C"),
            ("C951", "C"),
            ("C950", "C"),
            ("3494", "C"),
            ("9035", "C"),
        ],
        "EQA": [  # ATTACHED EQUIPMENT
            ("8053", "M"),
            ("C237", "C"),
        ],
        "EQD": [  # EQUIPMENT DETAILS
            ("8053", "M"),
            ("C237", "C"),
            ("C224", "C"),
            ("8077", "C"),
            ("8249", "C"),
            ("8169", "C"),
        ],
        "EQN": [  # NUMBER OF UNITS
            ("C523", "M"),
        ],
        "ERC": [  # APPLICATION ERROR INFORMATION
            ("C901", "M"),
        ],
        "ERP": [  # ERROR POINT DETAILS
            ("C701", "M"),
        ],
        "FCA": [  # FINANCIAL CHARGES ALLOCATION
            ("4471", "M"),
            ("C878", "C"),
        ],
        "FII": [  # FINANCIAL INSTITUTION INFORMATION
            ("3035", "M"),
            ("C078", "C"),
            ("C088", "C"),
            ("3207", "C"),
        ],
        "FNS": [  # FOOTNOTE SET
            ("C783", "M"),
            ("C082", "C"),
            ("4405", "C"),
            ("4513", "C"),
        ],
        "FNT": [  # FOOTNOTE
            ("C784", "M"),
            ("C082", "C"),
            ("4405", "C"),
            ("4513", "C"),
        ],
        "FTX": [  # FREE TEXT
            ("4451", "M"),
            ("4453", "C"),
            ("C107", "C"),
            ("C108", "C"),
            ("3453", "C"),
        ],
        "GDS": [  # NATURE OF CARGO
            ("C703", "C"),
        ],
        "GID": [  # GOODS ITEM DETAILS
            ("1496", "C"),
            ("C213", "C"),
            ("C213", "C"),
            ("C213", "C"),
        ],
        "GIN": [  # GOODS IDENTITY NUMBER
            ("7405", "M"),
            ("C208", "M"),
            ("C208", "C"),
            ("C208", "C"),
            ("C208", "C"),
            ("C208", "C"),
        ],
        "GIR": [  # RELATED IDENTIFICATION NUMBERS
            ("7297", "M"),
            ("C206", "M"),
            ("C206", "C"),
            ("C206", "C"),
            ("C206", "C"),
            ("C206", "C"),
        ],
        "GIS": [  # GENERAL INDICATOR
            ("C529", "M"),
        ],
        "GOR": [  # GOVERNMENTAL REQUIREMENTS
            ("8323", "C"),
            ("C232", "C"),
            ("C232", "C"),
            ("C232", "C"),
            ("C232", "C"),
        ],
        "GRU": [  # SEGMENT GROUP USAGE DETAILS
            ("9164", "M"),
            ("7299", "C"),
            ("6176", "C"),
            ("4513", "C"),
            ("1050", "C"),
        ],
        "HAN": [  # HANDLING INSTRUCTIONS
            ("C524", "C"),
            ("C218", "C"),
        ],
        "ICD": [  # INSURANCE COVER DESCRIPTION
            ("C330", "M"),
            ("C331", "M"),
        ],
        "IDE": [  # IDENTITY
            ("7495", "M"),
            ("C206", "M"),
            ("C082", "C"),
            ("4405", "C"),
            ("1222", "C"),
            ("C778", "C"),
            ("C240", "C"),
        ],
        "IHC": [  # PERSON CHARACTERISTIC
            ("3289", "M"),
            ("C818", "C"),
        ],
        "IMD": [  # ITEM DESCRIPTION
            ("7077", "C"),
            ("7081", "C"),
            ("C273", "C"),
            ("7383", "C"),
        ],
        "IND": [  # INDEX DETAILS
            ("C545", "C"),
            ("C546", "C"),
        ],
        "INP": [  # PARTIES TO INSTRUCTION
            ("C849", "C"),
            ("C522", "C"),
            ("C850", "C"),
            ("1229", "C"),
        ],
        "INV": [  # INVENTORY MANAGEMENT RELATED DETAILS
            ("4501", "C"),
            ("7491", "C"),
            ("4499", "C"),
            ("4503", "C"),
            ("C522", "C"),
        ],
        "IRQ": [  # INFORMATION REQUIRED
            ("C333", "M"),
        ],
        "LAN": [  # LANGUAGE
            ("3455", "M"),
            ("C508", "C"),
        ],
        "LIN": [  # LINE ITEM
            ("1082", "C"),
            ("1229", "C"),
            ("C212", "C"),
            ("C829", "C"),
            ("1222", "C"),
            ("7083", "C"),
        ],
        "LOC": [  # PLACE/LOCATION IDENTIFICATION
            ("3227", "M"),
            ("C517", "C"),
            ("C519", "C"),
            ("C553", "C"),
            ("5479", "C"),
        ],
        "MEA": [  # MEASUREMENTS
            ("6311", "M"),
            ("C502", "C"),
            ("C174", "C"),
            ("7383", "C"),
        ],
        "MEM": [  # MEMBERSHIP DETAILS
            ("7449", "M"),
            ("C942", "C"),
            ("C944", "C"),
            ("C945", "C"),
            ("C203", "C"),
            ("C960", "C"),
        ],
        "MKS": [  # MARKET/SALES CHANNEL INFORMATION
            ("7293", "M"),
            ("C332", "M"),
            ("1229", "C"),
        ],
        "MOA": [  # MONETARY AMOUNT
            ("C516", "M"),
        ],
        "MSG": [  # MESSAGE TYPE IDENTIFICATION
            ("C709", "M"),
            ("1507", "C"),
            ("4513", "C"),
        ],
        "NAD": [  # NAME AND ADDRESS
            ("3035", "M"),
            ("C082", "C"),
            ("C058", "C"),
            ("C080", "C"),
            ("C059", "C"),
            ("3164", "C"),
            ("3229", "C"),
            ("3251", "C"),
            ("3207", "C"),
        ],
        "NAT": [  # NATIONALITY
            ("3493", "M"),
            ("C042", "C"),
        ],
        "PAC": [  # PACKAGE
            ("7224", "C"),
            ("C531", "C"),
            ("C202", "C"),
            ("C402", "C"),
            ("C532", "C"),
        ],
        "PAI": [  # PAYMENT INSTRUCTIONS
            ("C534", "M"),
        ],
        "PAT": [  # PAYMENT TERMS BASIS
            ("4279", "M"),
            ("C110", "C"),
            ("C112", "C"),
        ],
        "PCD": [  # PERCENTAGE DETAILS
            ("C501", "M"),
        ],
        "PCI": [  # PACKAGE IDENTIFICATION
            ("4233", "C"),
            ("C210", "C"),
            ("8275", "C"),
            ("C827", "C"),
        ],
        "PDI": [  # PERSON DEMOGRAPHIC INFORMATION
            ("3499", "C"),
            ("C085", "C"),
            ("C101", "C"),
        ],
        "PGI": [  # PRODUCT GROUP INFORMATION
            ("5379", "M"),
            ("C288", "C"),
        ],
        "PIA": [  # ADDITIONAL PRODUCT ID
            ("4347", "M"),
            ("C212", "M"),
            ("C212", "C"),
            ("C212", "C"),
            ("C212", "C"),
            ("C212", "C"),
        ],
        "PIT": [  # PRICE ITEM LINE
            ("1082", "C"),
            ("1229", "C"),
            ("C292", "C"),
            ("7011", "C"),
            ("5495", "C"),
            ("1222", "C"),
            ("7083", "C"),
        ],
        "PNA": [  # PARTY NAME
            ("3035", "M"),
            ("C206", "C"),
            ("C082", "C"),
            ("3403", "C"),
            ("3397", "C"),
            ("C816", "C"),
            ("C816", "C"),
            ("C816", "C"),
            ("C816", "C"),
            ("C816", "C"),
        ],
        "PRC": [  # PROCESS IDENTIFICATION
            ("C242", "M"),
        ],
        "PRI": [  # PRICE DETAILS
            ("C509", "C"),
            ("5213", "C"),
        ],
        "PSD": [  # PHYSICAL SAMPLE DESCRIPTION
            ("4407", "C"),
            ("7039", "C"),
            ("C526", "C"),
            ("7045", "C"),
            ("7047", "C"),
            ("C514", "C"),
            ("C514", "C"),
            ("C514", "C"),
        ],
        "PTY": [  # PRIORITY
            ("4035", "M"),
            ("C585", "C"),
        ],
        "QTY": [  # QUANTITY
            ("C186", "M"),
        ],
        "QVR": [  # QUANTITY VARIANCES
            ("C279", "C"),
            ("4221", "C"),
            ("C960", "C"),
        ],
        "RCS": [  # REQUIREMENTS AND CONDITIONS
            ("7293", "M"),
            ("C550", "C"),
            ("1229", "C"),
        ],
        "REL": [  # RELATIONSHIP
            ("9141", "M"),
            ("C941", "C"),
        ],
        "RFF": [  # REFERENCE
            ("C506", "M"),
        ],
        "RNG": [  # RANGE DETAILS
            ("6167", "M"),
            ("C280", "C"),
        ],
        "RTE": [  # RATE DETAILS
            ("C128", "M"),
        ],
        "SAL": [  # REMUNERATION TYPE IDENTIFICATION
            ("C049", "C"),
        ],
        "SCC": [  # SCHEDULING CONDITIONS
            ("4017", "M"),
            ("4493", "C"),
            ("C329", "C"),
        ],
        "SCD": [  # STRUCTURE COMPONENT DEFINITION
            ("7497", "M"),
            ("C786", "C"),
            ("C082", "C"),
            ("4405", "C"),
            ("1222", "C"),
            ("C778", "C"),
            ("C240", "C"),
        ],
        "SEG": [  # SEGMENT IDENTIFICATION
            ("9166", "M"),
            ("1507", "C"),
            ("4513", "C"),
        ],
        "SEL": [  # SEAL NUMBER
            ("9308", "M"),
            ("C215", "C"),
            ("4517", "C"),
        ],
        "SEQ": [  # SEQUENCE DETAILS
            ("1245", "C"),
            ("C286", "C"),
        ],
        "SFI": [  # SAFETY INFORMATION
            ("7164", "M"),
            ("C814", "C"),
            ("C815", "C"),
            ("4513", "C"),
        ],
        "SGP": [  # SPLIT GOODS PLACEMENT
            ("C237", "M"),
            ("7224", "C"),
        ],
        "SGU": [  # SEGMENT USAGE DETAILS
            ("9166", "M"),
            ("7299", "C"),
            ("6176", "C"),
            ("7168", "C"),
            ("1050", "C"),
            ("1049", "C"),
            ("4513", "C"),
        ],
        "SPS": [  # SAMPLING PARAMETERS FOR SUMMARY STATISTICS
            ("C526", "C"),
            ("6074", "C"),
            ("C512", "C"),
            ("C512", "C"),
            ("C512", "C"),
            ("C512", "C"),
            ("C512", "C"),
        ],
        "STA": [  # STATISTICS
            ("6331", "M"),
            ("C527", "C"),
        ],
        "STC": [  # STATISTICAL CONCEPT
            ("C785", "M"),
            ("C082", "C"),
            ("4405", "C"),
            ("4513", "C"),
        ],
        "STG": [  # STAGES
            ("9421", "M"),
            ("6426", "C"),
            ("6428", "C"),
        ],
        "STS": [  # STATUS
            ("C601", "C"),
            ("C555", "C"),
            ("C556", "C"),
            ("C556", "C"),
            ("C556", "C"),
            ("C556", "C"),
            ("C556", "C"),
        ],
        "TAX": [  # DUTY/TAX/FEE DETAILS
            ("5283", "M"),
            ("C241", "C"),
            ("C533", "C"),
            ("5286", "C"),
            ("C243", "C"),
            ("5305", "C"),
            ("3446", "C"),
        ],
        "TCC": [  # TRANSPORT CHARGE/RATE CALCULATIONS
            ("C200", "C"),
            ("C203", "C"),
            ("C528", "C"),
            ("C554", "C"),
        ],
        "TDT": [  # DETAILS OF TRANSPORT
            ("8051", "M"),
            ("8028", "C"),
            ("C220", "C"),
            ("C228", "C"),
            ("C040", "C"),
            ("8101", "C"),
            ("C401", "C"),
            ("C222", "C"),
            ("8281", "C"),
        ],
        "TEM": [  # TEST METHOD
            ("C244", "C"),
            ("4419", "C"),
            ("3077", "C"),
            ("6311", "C"),
            ("7188", "C"),
            ("C515", "C"),
        ],
        "TMD": [  # TRANSPORT MOVEMENT DETAILS
            ("C219", "C"),
            ("8332", "C"),
            ("8341", "C"),
        ],
        "TMP": [  # TEMPERATURE
            ("6245", "M"),
            ("C239", "C"),
        ],
        "TOD": [  # TERMS OF DELIVERY OR TRANSPORT
            ("4055", "C"),
            ("4215", "C"),
            ("C100", "C"),
        ],
        "TPL": [  # TRANSPORT PLACEMENT
            ("C222", "M"),
        ],
        "TSR": [  # TRANSPORT SERVICE REQUIREMENTS
            ("C536", "C"),
            ("C233", "C"),
            ("C537", "C"),
            ("C703", "C"),
        ],
        "UNS": [  # SECTION CONTROL
            ("0081", "M"),
        ],
        "VLI": [  # VALUE LIST IDENTIFICATION
            ("C780", "M"),
            ("C082", "C"),
            ("4405", "C"),
            ("1514", "C"),
            ("1507", "C"),
            ("1505", "C"),
            ("C240", "C"),
            ("4513", "C"),
        ],
    }
}
